### ISSUE TITLE
AKP153E - Examples return panic with incorrect serial number on Windows 23H2

### ISSUE THREAD

**Issue by amsmith525** [OpenActionAPI/rust-elgato-streamdeck#25]
The following was tested on the same hardware configuration with dual boot Linux / Windows

Linux:

~/elgato-streamdeck/examples/simple$ cargo run -Znext-lockfile-bump
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/simple`
Akp153E 355499441494 4112
Connected to '355499441494' with version 'V2.293S.00.003'
Key count: 18
Touch point count: 0

Windows:

PS D:\elgato-streamdeck\examples\simple> cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target\debug\simple.exe`
Akp153E B52F50D4374D 4112
thread 'main' panicked at src/main.rs:20:124:
called `Result::unwrap()` on an `Err` value: HidError(HidApiError { message: "Get Input/Feature Report DeviceIoControl: (0x00000001) Incorrect function." })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\simple.exe` (exit code: 101)

**Comment by fightforlife** [comment]
Same issue here with Mirabox. On Linux it works.

```
cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target\debug\simple.exe`
MiraBoxHSV293S 7CB69C763555 26224
thread 'main' panicked at src\main.rs:20:124:
called `Result::unwrap()` on an `Err` value: HidError(HidApiError { message: "Get Input/Feature Report DeviceIoControl: (0x00000001) Unzulässige Funktion." })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\simple.exe` (exit code: 101)
```

**Comment by fightforlife** [comment]
If I uncomment Line 20 in the example the code goes on
https://github.com/streamduck-org/elgato-streamdeck/blob/e39a9d621effa13c157a70e372fef193865750bd/examples/simple/src/main.rs#L20

But then  it hangs here:
https://github.com/streamduck-org/elgato-streamdeck/blob/e39a9d621effa13c157a70e372fef193865750bd/examples/simple/src/main.rs#L63

**Comment by ninjadev64** [comment]
Interesting that it hangs, even if you reduce the number to something like 5?

**Comment by fightforlife** [comment]
With reduced time, the loop repeats every 5s but does not get any events/updates from the board.
And also nothing is displayed on the board.

**Comment by ninjadev64** [comment]
@ZCube @teras

**Comment by teras** [comment]
Which unwrap fails? Maybe put into separate lines and see? Is it the serial number?

I remember from my own experience with my Steamdeck device, that sometimes the firmware is fauly and manifests wrong SN.

But I think we solved this upstream.

**Comment by fightforlife** [comment]
On Linux both work for me.
On windows: 
- device.firmware_version().unwrap() fails with HidError(HidApiError from above.
- device.serial_number().unwrap() works

**Comment by fightforlife** [comment]
This is the output on Linux, which seems to work fine:
```
MiraBoxHSV293S 355499441494 26224
Connected to '355499441494' with version 'V2.293S.00.003'
Key count: 18
Touch point count: 0
Button 8 down
Button 8 up
```

Something interesting:
1. If I run the example on Linux (successfully)
2. then reboot into windows without unplugging/repluggin the Mirabox
3. run the example on windows (without the firmware_version)
4. I get the button presses registered on windows. / But the display does not change
5. If I replug, the button presses are no longer working.

**Comment by askolds11** [comment]
I've run two USBPcaps using Wireshark, I filtered out USB Interrupts, one is running the simple example (elgatostreamdeck.pcapng), the other is launching the Stream Dock application (streamdock.pcapng). Mirabox HSV 293S
[usbpcaps.zip](https://github.com/user-attachments/files/18497477/usbpcaps.zip)
Unfortunately I am unfamiliar with USB and currently don't have the time to experiment, but hope this helps. Let me know if you need one with the USB interrupts, but there's a lot of noise - they come in multiple times a second.

**Comment by askolds11** [comment]
I tried the latest hidapi-rs from git, which does not have a version on cargo yet, and at least the serial number there displays correctly. I have not been able to get the firmware version to work yet though - I am trying to understand these two (serial number and firmware version) before even beginning to attempt anything else.
I am not sure though if feature report is the correct thing to use for the firmware version , I think [this repo](https://github.com/MiraboxSpace/Windows-StreamDock-CPPSDK/blob/main/ConsoleApplication1/StreamDock293V3.cpp) is somewhat official and they seem to use getInputReport both on Linux (different repo from same user) and Windows:
```cpp
unsigned char *streamDock293::getFirmVersion(int lenth){
    return transport->getInputReport(lenth);
}
```

I have found [this repo](https://github.com/rigor789/mirabox-streamdock-node/blob/main/src/streamdock.ts#L95), where someone seems to have reverse engineered some Mirabox and does not use hidapi, which I will try to understand and try to create a minimal version in Rust that hopefully works.

**Comment by askolds11** [comment]
I managed to get firmware version to work in a separate test by using the rusb crate, I could not get feature_report to work no matter what - it would be ideal to get it to work using hidapi obviously, but at least there's a workaround if needed. Very quick and dirty code:
```rust
for device in rusb::devices().unwrap().iter() {
    let device_desc = device.device_descriptor().unwrap();
    if device_desc.vendor_id() != 0x5548 {
        continue;
    }
    println!("Bus {:03} Device {:03} ID {:04x}:{:04x}",
        device.bus_number(),
        device.address(),
        device_desc.vendor_id(),
        device_desc.product_id());
        let dev = device.open().unwrap();
        let mut buf = [0u8; 512];
        
        let result = dev.read_control(0xa1, 0x01, 0x100, 0, &mut buf, Duration::from_millis(5000));
        match result {
            Ok(x) => {
                println!("{}", x);
                println!("{:?}", buf);
            },
            Err(err) => println!("{}", err),
        }
}
```
I'm now inspecting the packets and it seems that all commands except CRT_CONNECT have their first byte cut off. I am not sure about if images lose their first byte though.
Stream Dock application:
![Image](https://github.com/user-attachments/assets/4509c623-7373-4337-9303-c7849521f7c0)

Simple example:
![Image](https://github.com/user-attachments/assets/ffb2a899-1f4b-4abc-8f48-b3a0c8f049d8)

(Last 5 bytes are size of image and key id, so it's ok that they're different)

I simply added 0x00 at the beginning to the byte vectors for now (could be anything really, it will get cut off) and it somewhat worked - images didn't upload, but set_brightness works, and clear_all_button_images makes the screen black (is this intended?)

**Comment by askolds11** [comment]
Changing
```rust
/// Writes data to [HidDevice]
pub fn write_data(device: &HidDevice, payload: &[u8]) -> Result<usize, HidError> {
    if cfg!(windows) || payload[0] != 0 {
        device.write(payload)
    } else {
        let mut buf = vec![0u8; payload.len() + 1];
        buf[0] = 0;
        buf[1..].copy_from_slice(payload);
        device.write(buf.as_slice())
    }
}
```
to
```rust
/// Writes data to [HidDevice]
pub fn write_data(device: &HidDevice, payload: &[u8]) -> Result<usize, HidError> {
    let mut buf = vec![0u8; payload.len() + 1];
    buf[0] = 0;
    buf[1..].copy_from_slice(payload);
    device.write(buf.as_slice())
}
```

Seems to fix everything except firmware version.

![Image](https://github.com/user-attachments/assets/2d6795dd-a6e0-48e9-8c82-45d48dc1fde0)

Obviously there's a reason it's there, need to research why it's there and how to process it correctly, but at least there's progress.

**Comment by askolds11** [comment]
From hidapi docs:
```rust
    /// Write an Output report to a HID device.
    ///
    /// The first byte of `data` must contain the Report ID. For
    /// devices which only support a single report, this must be set
    /// to 0x0. The remaining bytes contain the report data. Since
    /// the Report ID is mandatory, calls to `write()` will always
    /// contain one more byte than the report contains. For example,
    /// if a hid report is 16 bytes long, 17 bytes must be passed to
    /// `write()`, the Report ID (or 0x0, for devices with a
    /// single report), followed by the report data (16 bytes). In
    /// this example, the length passed in would be 17.
    /// `write()` will send the data on the first OUT endpoint, if
    /// one exists. If it does not, it will send the data through
    /// the Control Endpoint (Endpoint 0).
    ///
    /// If successful, returns the actual number of bytes written.
    pub fn write(&self, data: &[u8]) -> HidResult<usize> {
        self.inner.write(data)
    }
```

So the first byte needs to be the report id. For some reason this is coded to happen only on Linux in that snippet, so it doesn't happen on Windows and is the reason why it doesn't work.

The Elgato code has that header added before calling write_data, so it works on both Linux and Windows - the code has a check that if the first byte is not 0, it does not add a 0 before it, which is always for Elgato since it's report number is 0x02 - but I think this was a happy accident:

https://github.com/streamduck-org/elgato-streamdeck/pull/6#discussion_r1603433160

> There are cases where image transmission starts with 0 due to the absence of a header. I modified the write_data function in util.rs to handle this differently based on how the hidapi module handles it across different operating systems.

According to this, Elgato working that might be an accident. I am not sure if the 0 check is required - if I understand correctly, this can only happen when calling it from set_logo_image, but even in these cases I think there should still be a report number, which means this might be a bug on Linux as well, I don't know how to check this though.

So a correct fix might be:

- in the case of Elgatos, don't add anything, just write (works that way currently, by accident)
- in our case, add 0x00 before all write_data. This should be done either by adding it to all function calls, or by adding a parameter to the function, in which case the Elgato code should also be modified.
- but, it should still be determined, if the 0 check is needed for set_logo_image, where there is no header in the buffer (just data), but even in that case there should still be a report number (first byte), so I think the current code might lead to a corrupted image.

**Comment by askolds11** [comment]
WIP pull request https://github.com/streamduck-org/elgato-streamdeck/pull/27

**Comment by askolds11** [comment]
Windows functionality is fixed except serial number and firmware version.

Serial number is fixed by I presume these commits, but have to wait for new hidapi-rs crate version:
https://github.com/libusb/hidapi/commit/ff67c77daddbd8e61ad3873ac16f8edc005f943f
https://github.com/ruabmbua/hidapi-rs/commit/1c60b2feb26539e8ba60c6293fcc68ea455aa8c8

Firmware version no idea - since official repository is using getInputReport, that might work, but it's not supported on hidapi-rs on Windows yet. Best way to check would be to set up a C/C++ project with the getInputReport.

**Comment by nekename** [comment]
Starting in v0.11, this library only supports Elgato devices
